// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB9znZ9UDKYQ7PqrwCJg_ySa6gBjJTjZlg',
    appId: '1:658871434308:web:557072104f4079856e1011',
    messagingSenderId: '658871434308',
    projectId: 'airmoney-d4d12',
    authDomain: 'airmoney-d4d12.firebaseapp.com',
    storageBucket: 'airmoney-d4d12.firebasestorage.app',
    measurementId: 'G-15YRVG0HKD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC6CJ56_fObrHXgjB5J4x6zmcQYLJMG19c',
    appId: '1:658871434308:android:6008f1b42d49f41a6e1011',
    messagingSenderId: '658871434308',
    projectId: 'airmoney-d4d12',
    storageBucket: 'airmoney-d4d12.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJq4GwUs__lsAsDOc3rpPeH2D7Loa6UqM',
    appId: '1:658871434308:ios:d189bfe0019a841f6e1011',
    messagingSenderId: '658871434308',
    projectId: 'airmoney-d4d12',
    storageBucket: 'airmoney-d4d12.firebasestorage.app',
    iosClientId: '658871434308-1m8r85sari3poqllvnrspgretb7r2sp3.apps.googleusercontent.com',
    iosBundleId: 'bo.org.gastos.appGastos',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBJq4GwUs__lsAsDOc3rpPeH2D7Loa6UqM',
    appId: '1:658871434308:ios:d189bfe0019a841f6e1011',
    messagingSenderId: '658871434308',
    projectId: 'airmoney-d4d12',
    storageBucket: 'airmoney-d4d12.firebasestorage.app',
    iosClientId: '658871434308-1m8r85sari3poqllvnrspgretb7r2sp3.apps.googleusercontent.com',
    iosBundleId: 'bo.org.gastos.appGastos',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB9znZ9UDKYQ7PqrwCJg_ySa6gBjJTjZlg',
    appId: '1:658871434308:web:9c6c1dfa4d910e006e1011',
    messagingSenderId: '658871434308',
    projectId: 'airmoney-d4d12',
    authDomain: 'airmoney-d4d12.firebaseapp.com',
    storageBucket: 'airmoney-d4d12.firebasestorage.app',
    measurementId: 'G-KP0704YE9R',
  );
}
